//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitnuaVideoPlayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BitnuaVideoPlayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///    &lt;userSettings&gt;
        ///        &lt;BitnuaVideoPlayer.Properties.Settings&gt;
        ///            &lt;setting name=&quot;rmtCtrl&quot; serializeAs=&quot;Xml&quot;&gt;
        ///                &lt;value&gt;
        ///                    &lt;WindowStateDTO xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///                        xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///                        &lt;Height&gt;503&lt;/Height&gt;
        ///                        &lt;Width&gt;400&lt;/Width&gt;
        ///                        &lt;Left&gt;796&lt;/Left&gt;
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserConfTemplate {
            get {
                return ResourceManager.GetString("UserConfTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///    &lt;!-- 1. The &lt;iframe&gt; (and video player) will replace this &lt;div&gt; tag. --&gt;
        ///    &lt;div id=&quot;player&quot;&gt;&lt;/div&gt;
        ///
        ///    &lt;script&gt;
        ///        // 2. This code loads the IFrame Player API code asynchronously.
        ///        var tag = document.createElement(&apos;script&apos;);
        ///
        ///        tag.src = &quot;https://www.youtube.com/iframe_api&quot;;
        ///        var firstScriptTag = document.getElementsByTagName(&apos;script&apos;)[0];
        ///        firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
        ///
        ///        // 3. This funct [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YouTubeTemplateHtml {
            get {
                return ResourceManager.GetString("YouTubeTemplateHtml", resourceCulture);
            }
        }
    }
}
