//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitnuaVideoPlayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<WindowStateDTO xmlns:xsi=\"http://www.w3" +
            ".org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <" +
            "Height>400</Height>\r\n  <Width>400</Width>\r\n  <Left>0</Left>\r\n  <Top>0</Top>\r\n</W" +
            "indowStateDTO>")]
        public global::BitnuaVideoPlayer.WindowStateDTO rmtCtrl {
            get {
                return ((global::BitnuaVideoPlayer.WindowStateDTO)(this["rmtCtrl"]));
            }
            set {
                this["rmtCtrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<WindowStateDTO xmlns:xsi=\"http://www.w3" +
            ".org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <" +
            "Height>400</Height>\r\n  <Width>400</Width>\r\n  <Left>0</Left>\r\n  <Top>0</Top>\r\n</W" +
            "indowStateDTO>")]
        public global::BitnuaVideoPlayer.WindowStateDTO prWindow {
            get {
                return ((global::BitnuaVideoPlayer.WindowStateDTO)(this["prWindow"]));
            }
            set {
                this["prWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MainVmJson {
            get {
                return ((string)(this["MainVmJson"]));
            }
            set {
                this["MainVmJson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<WindowStateDTO xmlns:xsi=\"http://www.w3" +
            ".org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <" +
            "Height>0</Height>\r\n  <Width>0</Width>\r\n  <Left>0</Left>\r\n  <Top>0</Top>\r\n</Windo" +
            "wStateDTO>")]
        public global::BitnuaVideoPlayer.WindowStateDTO bannerWindow {
            get {
                return ((global::BitnuaVideoPlayer.WindowStateDTO)(this["bannerWindow"]));
            }
            set {
                this["bannerWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<WindowStateDTO xmlns:xsi=\"http://www.w3" +
            ".org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <" +
            "Height>0</Height>\r\n  <Width>0</Width>\r\n  <Left>0</Left>\r\n  <Top>0</Top>\r\n</Windo" +
            "wStateDTO>")]
        public global::BitnuaVideoPlayer.WindowStateDTO songInfoWindow {
            get {
                return ((global::BitnuaVideoPlayer.WindowStateDTO)(this["songInfoWindow"]));
            }
            set {
                this["songInfoWindow"] = value;
            }
        }
    }
}
